
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SHORT = 24;
  public static final int SIGNED = 25;
  public static final int IDENTIFIER = 87;
  public static final int BOOL = 36;
  public static final int ANDEQ = 82;
  public static final int GT = 50;
  public static final int ARROW = 56;
  public static final int BITSHIFTR = 63;
  public static final int CONST = 6;
  public static final int BITSHIFTL = 62;
  public static final int BITNOT = 59;
  public static final int PLUSEQ = 78;
  public static final int BITSHIFTREQ = 81;
  public static final int REGISTER = 21;
  public static final int ENUM = 12;
  public static final int IMAGINARY = 38;
  public static final int RBRACK = 44;
  public static final int SIZEOF = 26;
  public static final int COMMA = 46;
  public static final int RBRACE = 42;
  public static final int RPAREN = 40;
  public static final int LBRACK = 43;
  public static final int LT = 49;
  public static final int DOUBLE = 10;
  public static final int STRUCT = 28;
  public static final int LBRACE = 41;
  public static final int LPAREN = 39;
  public static final int XOREQ = 83;
  public static final int INTEGER_LITERAL = 85;
  public static final int NOT = 60;
  public static final int REMEQ = 77;
  public static final int BITSHIFTLEQ = 80;
  public static final int INLINE = 18;
  public static final int FLOAT = 14;
  public static final int GOTO = 16;
  public static final int EQ = 66;
  public static final int LONG = 20;
  public static final int PLUS = 52;
  public static final int QUESTION = 72;
  public static final int WHILE = 35;
  public static final int UNION = 31;
  public static final int ASSIGN = 48;
  public static final int CHAR = 5;
  public static final int SWITCH = 29;
  public static final int DO = 9;
  public static final int FOR = 15;
  public static final int STAR = 55;
  public static final int VOID = 33;
  public static final int EXTERN = 13;
  public static final int DIV = 54;
  public static final int RETURN = 23;
  public static final int BITOR = 69;
  public static final int ELSE = 11;
  public static final int STAREQ = 75;
  public static final int RESTRICT = 22;
  public static final int REMAINDER = 61;
  public static final int BREAK = 3;
  public static final int GTEQ = 65;
  public static final int DOT = 47;
  public static final int INT = 19;
  public static final int EOF = 0;
  public static final int SEMICOLON = 45;
  public static final int DEFAULT = 8;
  public static final int MINUS = 53;
  public static final int LTEQ = 64;
  public static final int OR = 71;
  public static final int BITAND = 58;
  public static final int error = 1;
  public static final int DIVEQ = 76;
  public static final int CONTINUE = 7;
  public static final int IF = 17;
  public static final int UNSIGNED = 32;
  public static final int MINUSMINUS = 57;
  public static final int COLON = 73;
  public static final int OREQ = 84;
  public static final int VOLATILE = 34;
  public static final int CASE = 4;
  public static final int PLUSPLUS = 51;
  public static final int NEQ = 67;
  public static final int AND = 70;
  public static final int COMPLEX = 37;
  public static final int ELLIPSIS = 74;
  public static final int STATIC = 27;
  public static final int TYPEDEF = 30;
  public static final int AUTO = 2;
  public static final int XOR = 68;
  public static final int FLOATING_POINT_LITERAL = 86;
  public static final int MINUSEQ = 79;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AUTO",
  "BREAK",
  "CASE",
  "CHAR",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "DO",
  "DOUBLE",
  "ELSE",
  "ENUM",
  "EXTERN",
  "FLOAT",
  "FOR",
  "GOTO",
  "IF",
  "INLINE",
  "INT",
  "LONG",
  "REGISTER",
  "RESTRICT",
  "RETURN",
  "SHORT",
  "SIGNED",
  "SIZEOF",
  "STATIC",
  "STRUCT",
  "SWITCH",
  "TYPEDEF",
  "UNION",
  "UNSIGNED",
  "VOID",
  "VOLATILE",
  "WHILE",
  "BOOL",
  "COMPLEX",
  "IMAGINARY",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "ASSIGN",
  "LT",
  "GT",
  "PLUSPLUS",
  "PLUS",
  "MINUS",
  "DIV",
  "STAR",
  "ARROW",
  "MINUSMINUS",
  "BITAND",
  "BITNOT",
  "NOT",
  "REMAINDER",
  "BITSHIFTL",
  "BITSHIFTR",
  "LTEQ",
  "GTEQ",
  "EQ",
  "NEQ",
  "XOR",
  "BITOR",
  "AND",
  "OR",
  "QUESTION",
  "COLON",
  "ELLIPSIS",
  "STAREQ",
  "DIVEQ",
  "REMEQ",
  "PLUSEQ",
  "MINUSEQ",
  "BITSHIFTLEQ",
  "BITSHIFTREQ",
  "ANDEQ",
  "XOREQ",
  "OREQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "IDENTIFIER"
  };
}

